---
title: "Day XX Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(ggplot2)
library(ggraph)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}


binsum<-function(x){
  s<-0
  while(x>1){
    s<-s+x%%2
    x<-x%/%2}
  s<-s+1}
sapply(1:16,binsum)
```
```{r}
wallmein<-function(sx=0,sy=0,ex=7,ey=4,fn=10){
  ### set up the dictionary & queue
  beenthere<-dict()
  pq<-priority_queue()
  s<-c(sx,sy,0)
  ### push the starting point
  pq$push(s,pri=0)
  while(pq$size()>0){
    curr<-pq$pop()
    ### if out of bounds,move on
    if(curr[1]<0){next}
    if(curr[2]<0){next}
    ### if at the end, stop
    if(curr[1]==ex&&curr[2]==ey){return(list(curr,beenthere))}
    ### if you've been there before, stop
    if(beenthere$has(c(curr[1],curr[2]))){next}
    ### check to see if it's a wall or a space.
    clc<-(curr[1]^2)+(3*curr[1])+(2*curr[1]*curr[2])+(curr[2])+(curr[2]^2)+fn
    ### if it is a wall - stop, but save the answer into the list of places it has been
    if(binsum(clc)%%2==1){
      beenthere$set(c(curr[1],curr[2]),"#")
      next}else{
        ### otherwise, just add to the places it has been
        beenthere$set(c(curr[1],curr[2]),".")}
    ### find the possible next points and put them on the queue
    nxts<-list(c(-1,0),c(1,0),c(0,1),c(0,-1))
    for(i in 1:4){
      a<-nxts[[i]]
      a<-a+c(curr[1],curr[2])
      pri<-curr[3]+sum(abs(c(curr[1],curr[2])-c(ex,ey)))
      a<-c(a,curr[3]+1)
      pq$push(a,-pri)}}
  beenthere}
```




```{r}
p1<-wallmein(1,1,7,4,10)
part1<-p1[[1]][3]
part1
```
```{r,echo=FALSE}
gr<-t(as.data.frame(p1[[2]]$as_list()))
gr<-as.data.frame(cbind(row.names(gr),gr))
gr<-gr %>% rowwise %>% mutate(V1=str_sub(V1,3,-2)) %>%
  mutate(x=as.numeric(str_split_i(V1,"\\.\\.",1)),y=as.numeric(str_split_i(V1,"\\.\\.",2)))%>%
  mutate(V3=ifelse(V2=="#",1,0))

```


```{r,echo=FALSE}
ggplot(data=gr,aes(x=x,y=y,colour=V2))+
  geom_point()+
  geom_point(aes(x=7,y=4),colour="blue",size=6)+
  scale_color_manual(values=c("black", "#ff1111"))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill="#EFEFEF"),
        legend.position="none")+
  scale_y_reverse()+
  coord_fixed()

```
## Part 2
Much the same, but do a flood fill.

```{r}
floodthewalls<-function(sx=0,sy=0,fn=10){
##creating two dictionaries & the queue
  beenthere<-dict()
  walls<-dict()
  pq<-priority_queue()
  s<-c(sx,sy,0)
  pq$push(s,pri=0)
  while(pq$size()>0){
    curr<-pq$pop()
    ### if less than 0, stop
    if(curr[1]<0){next}
    if(curr[2]<0){next}
    ### if greater than 50, put that point in the "walls" dictionary, and stop
    if(curr[3]>50){
      walls$set(c(curr[1],curr[2]),"F")
      next} 
    ### if you have been there before, stop
    if(beenthere$has(c(curr[1],curr[2]))||walls$has(c(curr[1],curr[2]))){next}
    ### check to see if a wall or not
    clc<-(curr[1]^2)+(3*curr[1])+(2*curr[1]*curr[2])+(curr[2])+(curr[2]^2)+fn
    if(binsum(clc)%%2==1){
      ### if it is a wall, set that into the "walls" dictionary
      walls$set(c(curr[1],curr[2]),"#")
      next}else{
        ### otherwise, find the next possible points and repeat
        beenthere$set(c(curr[1],curr[2]),".")}
    nxts<-list(c(-1,0),c(1,0),c(0,1),c(0,-1))
    for(i in 1:4){
      a<-nxts[[i]]
      a<-a+c(curr[1],curr[2])
      a<-c(a,curr[3]+1)
      pq$push(a,-a[3])}}
  ##return both the walls and the valid spaces
  list(beenthere,walls)}
```




```{r}
p2<-floodthewalls(1,1,10)
### the answer is the length of the "valid" dictionary
part2<-p2[[1]]$size()
part2
```
```{r,echo=FALSE}
gr2<-t(as.data.frame(p2[[2]]$as_list()))
gr2<-as.data.frame(cbind(row.names(gr2),gr2))
gr2<-gr2 %>% rowwise %>% mutate(V1=str_sub(V1,3,-2)) %>%
  mutate(x=as.numeric(str_split_i(V1,"\\.\\.",1)),y=as.numeric(str_split_i(V1,"\\.\\.",2)))

gr3<-t(as.data.frame(p2[[1]]$as_list()))
gr3<-as.data.frame(cbind(row.names(gr3),gr3))
gr3<-gr3 %>% rowwise %>% mutate(V1=str_sub(V1,3,-2)) %>%
  mutate(x=as.numeric(str_split_i(V1,"\\.\\.",1)),y=as.numeric(str_split_i(V1,"\\.\\.",2)))

cmb<-rbind(gr2,gr3)

ggplot(data=cmb,aes(x=x,y=y,colour=V2))+
  geom_point()+
  scale_color_manual(values=c("black", "#ff1111","#0000FF"))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill="#EFEFEF"),
        legend.position="none")+
  scale_y_reverse()+
  coord_fixed()

```

